<?php
/**
 * BlobStoreQuotaResultXOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.16.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Apiida\Nexus\Client\Model;

use PHPUnit\Framework\TestCase;

/**
 * BlobStoreQuotaResultXOTest Class Doc Comment
 *
 * @category    Class
 * @description BlobStoreQuotaResultXO
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BlobStoreQuotaResultXOTest extends TestCase
{


    /**
     * Test "BlobStoreQuotaResultXO"
     */
    public function testBlobStoreQuotaResultXO()
    {
    }

    /**
     * Test attribute "is_violation"
     */
    public function testPropertyIsViolation()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "blob_store_name"
     */
    public function testPropertyBlobStoreName()
    {
    }
}
