<?php
/**
 * ReadOnlyStateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.16.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Apiida\Nexus\Client\Model;

use PHPUnit\Framework\TestCase;

/**
 * ReadOnlyStateTest Class Doc Comment
 *
 * @category    Class
 * @description ReadOnlyState
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReadOnlyStateTest extends TestCase
{

    /**
     * Test "ReadOnlyState"
     */
    public function testReadOnlyState()
    {
    }

    /**
     * Test attribute "system_initiated"
     */
    public function testPropertySystemInitiated()
    {
    }

    /**
     * Test attribute "summary_reason"
     */
    public function testPropertySummaryReason()
    {
    }

    /**
     * Test attribute "frozen"
     */
    public function testPropertyFrozen()
    {
    }
}
