<?php
/**
 * BlobStoreApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.16.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Apiida\Nexus\Client\Api;

use Apiida\Nexus\Client\Configuration;
use Apiida\Nexus\Client\ApiException;
use Apiida\Nexus\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BlobStoreApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BlobStoreApiTest extends TestCase
{

    /**
     * Test case for quotaStatus
     *
     * Get quota status for a given blob store.
     *
     */
    public function testQuotaStatus()
    {
    }
}
