<?php
/**
 * LifecycleApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.16.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Apiida\Nexus\Client\Api;

use Apiida\Nexus\Client\Configuration;
use Apiida\Nexus\Client\ApiException;
use Apiida\Nexus\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * LifecycleApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LifecycleApiTest extends TestCase
{

    /**
     * Test case for bounce
     *
     * Bounce lifecycle phase.
     *
     */
    public function testBounce()
    {
    }

    /**
     * Test case for getPhase
     *
     * Get current lifecycle phase.
     *
     */
    public function testGetPhase()
    {
    }

    /**
     * Test case for setPhase
     *
     * Move to new lifecycle phase.
     *
     */
    public function testSetPhase()
    {
    }
}
