<?php
/**
 * ScriptApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nexus Repository Manager REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.16.1-02
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Apiida\Nexus\Client\Api;

use Apiida\Nexus\Client\Configuration;
use Apiida\Nexus\Client\ApiException;
use Apiida\Nexus\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ScriptApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ScriptApiTest extends TestCase
{

    /**
     * Test case for add
     *
     * Add a new script.
     *
     */
    public function testAdd()
    {
    }

    /**
     * Test case for browse
     *
     * List all stored scripts.
     *
     */
    public function testBrowse()
    {
    }

    /**
     * Test case for delete
     *
     * Delete stored script by name.
     *
     */
    public function testDelete()
    {
    }

    /**
     * Test case for edit
     *
     * Update stored script by name.
     *
     */
    public function testEdit()
    {
    }

    /**
     * Test case for read
     *
     * Read stored script by name.
     *
     */
    public function testRead()
    {
    }

    /**
     * Test case for run1
     *
     * Run stored script by name.
     *
     */
    public function testRun1()
    {
    }
}
